name: Workflow
on:
  push:
    branches:
      - master
      - with-dev-master
jobs:
  lint:
    name: Lint with PHP_CodeSniffer
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: [7.1, 7.2, 7.3, 7.4]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@2.1.3
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: prestissimo
      - name: Install dependencies
        run: composer install --ignore-platform-reqs --no-progress --no-suggest --prefer-dist
      - name: Lint with PHP_CodeSniffer
        if: always()
        run: vendor/bin/phpcs
      - name: Fix with PHP_CodeSniffer
        if: always()
        run: vendor/bin/phpcbf
